### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by torecki** [Automating-GIS-processes/CSC18#1]
Hello, 
first of all I would like to express my greatest respect and gratitude. The course is wonderful, I've been looking for it for a long time.
But I have a request: It would be nice if you could add more examples for visualization. It would be especially nice if the visualization could be done directly in the Jupyter notebook. I would like to be able to display points and polygons and all analyses graphically.

Thanks in advance

**Comment by VuokkoH** [comment]
Hi! We hope you have noticed the most recent version of the course materials: https://automating-gis-processes.github.io/2018/ and the related exercises: https://github.com/AutoGIS-2018/. There are already quite a few visualization examples which work directly in Jupyter notebook, and we will again develop the course further this year :) Thanks for your interest!
